thinkphp5.0guide-step1/application/index/view/teacher_course/index.html

教师端下课程原型增加向班级跳转

---

thinkphp5.0guide-step1/application/common/validate/Term.php
thinkphp5.0guide-step1/application/index/controller/AdminTermController.php
thinkphp5.0guide-step1/application/index/view/admin_mould/index.html
thinkphp5.0guide-step1/application/index/view/admin_term/add.html
thinkphp5.0guide-step1/application/index/view/admin_term/edit.html
thinkphp5.0guide-step1/application/index/view/admin_term/index.html
thinkphp5.0guide-step1/sql/yunzhi_term.sql

管理员端学期的C层和V层的完善

---

thinkphp5.0guide-step1/application/common/model/Mould.php
thinkphp5.0guide-step1/application/index/controller/AdminMouldController.php
thinkphp5.0guide-step1/application/index/view/admin_mould/index.html
thinkphp5.0guide-step1/sql/yunzhi_aisle.sql
thinkphp5.0guide-step1/sql/yunzhi_mould.sql
thinkphp5.0guide-step1/sql/yunzhi_seat.sql
thinkphp5.0guide-step1/sql/yunzhi_term.sql

管理员端模板的分页查找和新建数据库

---

thinkphp5.0guide-step1/application/common/model/Klass.php
thinkphp5.0guide-step1/application/common/validate/Klass.php
thinkphp5.0guide-step1/application/index/controller/KlassController.php
thinkphp5.0guide-step1/application/index/view/klass/edit.html
thinkphp5.0guide-step1/application/index/view/klass/index.html

教师管理下班级增删改查下编辑一条班级

---

thinkphp5.0guide-step1/application/index/controller/KlassController.php
thinkphp5.0guide-step1/application/index/view/klass/index.html

教师管理下班级增删改查下删除一条班级

---

thinkphp5.0guide-step1/sql/tp1Student.sql

学生数据库的修改属性

---

thinkphp5.0guide-step1/application/common/validate/Aisle.php
thinkphp5.0guide-step1/application/common/validate/Mould.php
thinkphp5.0guide-step1/application/common/validate/Seat.php
thinkphp5.0guide-step1/application/common/validate/Term.php
thinkphp5.0guide-step1/application/index/controller/AdminMouldController.php
thinkphp5.0guide-step1/application/index/controller/AdminTermController.php
thinkphp5.0guide-step1/application/index/view/admin_mould/check.html
thinkphp5.0guide-step1/application/index/view/admin_mould/edit.html
thinkphp5.0guide-step1/application/index/view/admin_mould/index.html
thinkphp5.0guide-step1/application/index/view/admin_term/index.html

管理员端模板的编辑与删除

---

thinkphp5.0guide-step1/sql/yunzhi_course.sql
thinkphp5.0guide-step1/sql/yunzhi_grade.sql

建立成绩数据表并增加课程数据表部分属性

---

thinkphp5.0guide-step1/application/common/model/Student.php
thinkphp5.0guide-step1/application/common/model/Teacher.php
thinkphp5.0guide-step1/application/index/controller/AdminTeacherController.php
thinkphp5.0guide-step1/application/index/controller/TeacherStudentController.php
thinkphp5.0guide-step1/application/index/view/admin_teacher/index.html
thinkphp5.0guide-step1/application/index/view/teacher_student/index.html

管理员端教师管理修复

---

thinkphp5.0guide-step1/application/index/controller/AdminMouldController.php
thinkphp5.0guide-step1/application/index/controller/AdminRoomController.php
thinkphp5.0guide-step1/application/index/view/admin_mould/add.html
thinkphp5.0guide-step1/application/index/view/admin_mould/check.html
thinkphp5.0guide-step1/application/index/view/admin_mould/edit.html
thinkphp5.0guide-step1/application/index/view/admin_mould/index.html
thinkphp5.0guide-step1/application/index/view/admin_room/add.html
thinkphp5.0guide-step1/application/index/view/admin_room/edit.html
thinkphp5.0guide-step1/application/index/view/admin_room/index.html
thinkphp5.0guide-step1/application/index/view/admin_term/index.html

管理员端教室管理分页查找和模板查看实现上下页查看

---

thinkphp5.0guide-step1/application/common/model/Student.php
thinkphp5.0guide-step1/application/common/validate/Student.php
thinkphp5.0guide-step1/application/index/controller/KlassController.php
thinkphp5.0guide-step1/application/index/view/klass/check.html
thinkphp5.0guide-step1/application/index/view/klass/student_add.html
thinkphp5.0guide-step1/application/index/view/klass/student_edit.html

教师端班级管理中对学生名单增删改功能 

---

thinkphp5.0guide-step1/sql/tp1Student.sql

学生数据表对于一些属性值能否为空的修改

---

thinkphp5.0guide-step1/application/index/controller/KlassController.php
thinkphp5.0guide-step1/application/index/view/klass/check.html

教师端班级管理中某学生在其班级列表下的查找

---

thinkphp5.0guide-step1/application/common/model/Teacher.php
thinkphp5.0guide-step1/application/index/controller/KlassController.php
thinkphp5.0guide-step1/application/index/view/klass/add.html
thinkphp5.0guide-step1/application/index/view/klass/check.html
thinkphp5.0guide-step1/application/index/view/klass/edit.html
thinkphp5.0guide-step1/application/index/view/klass/index.html
thinkphp5.0guide-step1/application/index/view/klass/student_add.html
thinkphp5.0guide-step1/application/index/view/klass/student_edit.html
thinkphp5.0guide-step1/application/index/view/teacher/index.html
thinkphp5.0guide-step1/application/index/view/teacher_course/index.html
thinkphp5.0guide-step1/application/index/view/teacher_student/add.html
thinkphp5.0guide-step1/application/index/view/teacher_student/edit.html
thinkphp5.0guide-step1/application/index/view/teacher_student/index.html
thinkphp5.0guide-step1/sql/tp1Student.sql
thinkphp5.0guide-step1/sql/yunzhi_klass.sql

教师端下班级管理部分路由的修正

---

thinkphp5.0guide-step1/application/common/model/Student.php
thinkphp5.0guide-step1/application/common/model/Teacher.php
thinkphp5.0guide-step1/application/common/validate/Room.php
thinkphp5.0guide-step1/application/index/controller/AdminMouldController.php
thinkphp5.0guide-step1/application/index/controller/AdminRoomController.php
thinkphp5.0guide-step1/application/index/view/admin_room/add.html
thinkphp5.0guide-step1/application/index/view/admin_room/choose.html
thinkphp5.0guide-step1/application/index/view/admin_room/edit.html
thinkphp5.0guide-step1/application/index/view/admin_room/index.html

管理员端教室的编辑和删除

---

thinkphp5.0guide-step1/application/common/model/Teacher.php
thinkphp5.0guide-step1/application/index/controller/TeacherController.php
thinkphp5.0guide-step1/application/index/controller/TeacherCourseController.php
thinkphp5.0guide-step1/application/index/view/teacher/onclass.html
thinkphp5.0guide-step1/application/index/view/teacher_course/add.html
thinkphp5.0guide-step1/application/index/view/teacher_course/edit.html
thinkphp5.0guide-step1/application/index/view/teacher_course/index.html
thinkphp5.0guide-step1/sql/tp1.sql

教师端课程管理关联教师

---

thinkphp5.0guide-step1/application/common/model/Teacher.php
thinkphp5.0guide-step1/application/common/validate/Student.php
thinkphp5.0guide-step1/application/index/controller/TeacherController.php
thinkphp5.0guide-step1/application/index/controller/TeacherCourseController.php
thinkphp5.0guide-step1/application/index/controller/TeacherStudentController.php
thinkphp5.0guide-step1/application/index/view/teacher/onclass.html
thinkphp5.0guide-step1/application/index/view/teacher_course/add.html
thinkphp5.0guide-step1/application/index/view/teacher_course/edit.html
thinkphp5.0guide-step1/application/index/view/teacher_course/index.html
thinkphp5.0guide-step1/sql/tp1.sql

删除学生时删除对应的成绩114

---

thinkphp5.0guide-step1/application/common/validate/Room.php
thinkphp5.0guide-step1/application/index/controller/AdminMouldController.php
thinkphp5.0guide-step1/application/index/controller/AdminRoomController.php
thinkphp5.0guide-step1/application/index/view/admin_mould/add.html
thinkphp5.0guide-step1/application/index/view/admin_mould/check.html
thinkphp5.0guide-step1/application/index/view/admin_mould/edit.html
thinkphp5.0guide-step1/application/index/view/admin_mould/index.html
thinkphp5.0guide-step1/application/index/view/admin_room/add.html
thinkphp5.0guide-step1/application/index/view/admin_room/choose.html
thinkphp5.0guide-step1/application/index/view/admin_room/edit.html
thinkphp5.0guide-step1/application/index/view/admin_room/index.html
thinkphp5.0guide-step1/application/index/view/admin_teacher/add.html
thinkphp5.0guide-step1/application/index/view/admin_teacher/edit.html
thinkphp5.0guide-step1/application/index/view/admin_teacher/index.html
thinkphp5.0guide-step1/application/index/view/admin_term/index.html
thinkphp5.0guide-step1/application/index/view/index.html
thinkphp5.0guide-step1/sql/yunzhi_aisle.sql
thinkphp5.0guide-step1/sql/yunzhi_mould.sql
thinkphp5.0guide-step1/sql/yunzhi_room.sql
thinkphp5.0guide-step1/sql/yunzhi_seat.sql
thinkphp5.0guide-step1/sql/yunzhi_term.sql

管理员端的教室新增和各个界面的跳转

---

thinkphp5.0guide-step1/application/index/controller/AdminMouldController.php
thinkphp5.0guide-step1/application/index/view/admin_mould/edit.html

管理员端模板的完善和修改bug

---

thinkphp5.0guide-step1/application/index/controller/ExcelController.php
thinkphp5.0guide-step1/application/index/controller/TeacherController.php
thinkphp5.0guide-step1/application/index/controller/TeacherStudentController.php
thinkphp5.0guide-step1/application/index/view/teacher_student/index.html
thinkphp5.0guide-step1/application/index/view/teacher_student/select.html

成绩导出与模板下载137

---

thinkphp5.0guide-step1/application/index/controller/TeacherCourseController.php
thinkphp5.0guide-step1/application/index/view/teacher_course/index.html

教师端课程管理完善147

---

thinkphp5.0guide-step1/application/index/controller/AdminTeacherController.php
thinkphp5.0guide-step1/application/index/controller/KlassController.php
thinkphp5.0guide-step1/application/index/view/admin_teacher/index.html

管理员端教师管理查询161

---

thinkphp5.0guide-step1/application/index/controller/ExcelController.php
thinkphp5.0guide-step1/application/index/controller/KlassController.php
thinkphp5.0guide-step1/application/index/controller/TeacherController.php
thinkphp5.0guide-step1/application/index/view/klass/edit.html

随机点名bug修复170

---

thinkphp5.0guide-step1/application/index/controller/ExcelController.php
thinkphp5.0guide-step1/application/index/controller/KlassController.php
thinkphp5.0guide-step1/application/index/view/klass/edit.html

班级管理文件模板下载

---

thinkphp5.0guide-step1/application/common/validate/Student.php
thinkphp5.0guide-step1/application/index/controller/KlassController.php
thinkphp5.0guide-step1/application/index/controller/TeacherStudentController.php

根据学生信息生成班级人数173

---

thinkphp5.0guide-step1/application/index/controller/TeacherCourseController.php

增加课程同时增加成绩信息191

---

thinkphp5.0guide-step1/application/index/controller/ScoreController.php
thinkphp5.0guide-step1/application/index/controller/TeacherController.php
thinkphp5.0guide-step1/application/index/view/teacher/index.html
thinkphp5.0guide-step1/application/index/view/teacher/onclass.html
thinkphp5.0guide-step1/application/index/view/teacher_student/add.html

教师端上课bug 修复196

---

thinkphp5.0guide-step1/application/index/controller/TeacherStudentController.php
thinkphp5.0guide-step1/application/index/view/klass/index.html
thinkphp5.0guide-step1/application/index/view/score/edit.html
thinkphp5.0guide-step1/application/index/view/score/index.html

教师端菜单修复215

---

thinkphp5.0guide-step1/application/index/controller/TeacherStudentController.php

成绩导入bug修复212
